package se.natusoft.seagull.api.model

import se.natusoft.lic.annotation.BinariesAvailableAt
import se.natusoft.lic.annotation.Human_Software_License_1_0
import se.natusoft.lic.annotation.SourceAvailableAt

@Human_Software_License_1_0
@SourceAvailableAt("https://github.com/tombensve/Seagull")
@BinariesAvailableAt( "https://repo.repsy.io/mvn/tombensve/natusoft-os/" )

/**
 * This represents a  message id
 *
 * Since I want to be able to use JSON, even though not strictly required,
 * and an UUID generated String, I'm forced to encapsulate it and provide
 * a toString() method to provide value in JSON compatible type. Java does
 * not allow you to extend String either!
 *
 * This means that I cannot pass an instance of this as a value, thus
 * requiring doing a toString() on the MessageId object. This really
 * annoys me!
 *
 * But having this MessageId class makes things a bit clearer than  just
 * setting a String value generated by an UUID. So toString() still needs
 * to be called to get a value that can be sent in a message.
 *
 * I am hoping that Groovy is so nice that passing this as a MessageId to
 * a String value will automatically call toString() to convert it to a
 * String value!
 */
class SGMessageId {
    
    private String msgId
    
    /**
     * Creates a new SGMessageId.
     */
    SGMessageId() {
        this.msgId = UUID.randomUUID(  ).toString(  )
    }
    
    /**
     * @return A String representation of this SGMessageId.
     */
    String toString() { getId() }
    
    // ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ //
    
    /**
     * @return Returns same String as toString().
     */
    String getId() { this.msgId }
}
